#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

cat > $payload <&0

configure_credhub
credhub_get_schema > ${schema}

version >&3
