#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

cat > $payload <&0

configure_credhub

schema_file=$(jq -r '.params.schema_file' < $payload)
credhub set --name=$(schema_path) --type=json --value="$(cat ${schema_file})" > /dev/null

credhub_get_schema > ${schema}

version >&3
